a=input("digiti algo :")
print('O tipo desse valor é',type(a))
print("so tem eespacos?",a.isspace())
print("E e um numero",a.isnumeric())
print("E e um alfabetco",a.isalpha())
print("E e um alfa numerico",a.isalnum())
print("Esta em maiusculas",a.isupper())
print("Esta em miinusculas",a.islower())
print("Esta em captalizada",a.istitle())
